# Generated by Django 4.0.5 on 2022-07-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Taskassign',
        ),
    ]
